### ISSUE TITLE
Maybe there are some mistakes in pg.py

### ISSUE THREAD

**Issue by Ctiely** [liber145/rlpack#2]
in function _parse_trajectory:
```
tsum = 0
for i, (s, a, r) in enumerate(reversed(trajectory)):
    tsum = self._discount * tsum + r
    allr_batch[i] = tsum
```
shoule be written as follows:
```
tsum = 0
for i, (s, a, r) in enumerate(reversed(trajectory)):
    tsum = self._discount * tsum + r
    allr_batch[n - i - 1] = tsum
```

**Comment by liber145** [comment]
Yes, you are right! Thank you!

**Comment by AlbertPYB** [comment]
Program running needs import the function make_ramatari as follows:
 from rlpack.environment import make_ramatari
but I can't find  make_ramatari in the environment file, can you help me?  
Thank you very much!
