### ISSUE TITLE
tqdm.write() invalid syntax

### ISSUE THREAD

**Issue by AlbertPYB** [liber145/rlpack#3]
when I run the code,
  tqdm.write(f"{i}th. totrew={totrew}, totlen={totlen}")
SyntaxError: invalid syntax
but I don't know the reason, may you help me solve the problem?

**Comment by liber145** [comment]
The reason may be your python version. Format string with f"...." is a new feature after python3.6. 
https://realpython.com/python-f-strings/ You could also rewrite it as `print(i, "  totrew=", totrew, "totlen=", totlen)`

**Comment by AlbertPYB** [comment]
OK, Got;  Thank you~

**Comment by liber145** [comment]
You are welcome :)
