### ISSUE TITLE
import make_ramatari

### ISSUE THREAD

**Issue by AlbertPYB** [liber145/rlpack#4]
Program running needs import the function make_ramatari as follows:
from rlpack.environment import make_ramatari
but I can't find make_ramatari in the environment file, can you help me?
Thank you very much!

**Comment by liber145** [comment]
Thank you for pointing out this! :) There are some bugs after reconstruction. I will check it tomorrow.

**Comment by liber145** [comment]
To use `make_ramatari`, you need to install rlpack by `python setup.py install`. Then you can run `make_ramatari`. The environment will work after the installation. But it is not easy to get reinforcement algorithm work on it.
